export function generateTemplateHtml(
  name: string,
  files: Record<string, string>,
) {
  return `<html lang="en">
<head></head>
<body>

<form id="mainForm" method="post" action="https://stackblitz.com/run" target="_self">
<input type="hidden" name="project[files][index.html]" value="<button>Click Me</button>
">
${Object.entries(files)
  .map(
    ([
      file,
      contentOrUrl,
    ]) => `<input type="hidden" name="project[files][${file}]" value=${JSON.stringify(contentOrUrl)}>`,
  )
  .join("\n")}
<input type="hidden" name="project[description]" value="generated by https://pkg.pr.new">
<input type="hidden" name="project[dependencies]" value="{&quot;rxjs&quot;:&quot;5.5.6&quot;}">
<input type="hidden" name="project[template]" value="node">
<input type="hidden" name="project[title]" value="${name}">
</form>
<script>document.getElementById("mainForm").submit();</script>

</body></html>`;
}
