name: CI Linting

on:
  pull_request:

jobs:
  linting:
    name: Run Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - run: |
          npm install -g corepack@latest
          corepack enable

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint JavaScript
        run: pnpm run lint:js

      - name: Check formatting
        run: pnpm run lint:format

      - name: Type checking (non-blocking)
        run: pnpm run lint:types
        continue-on-error: true
